apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: pubsub-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: publisher
        image: rochabr/dapr-publisher:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080