apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr-conductor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: agent
    repoURL: oci://public.ecr.aws/diagrid/conductor-charts
    targetRevision: 0.333.0
    helm:
      releaseName: argo-cluster
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/service/namespace
        - /spec/conversion/webhook/clientConfig/caBundle