agent:
  goMemLimit: 600MiB
  image: >-
    us-central1-docker.pkg.dev/prj-common-p-shared-79896/reg-p-common-docker-public/agent:0.365.0
  installDependencies: false
  key: >-
    agentkey||gcp||projects/1082159079122/secrets/886d7b89-cd17-4596-8b94-6ff257bb153f/versions/1
  keyB64: YWNhMDVkMTItZDBhNi00YzJjLTlmMTAtODVmOGU3YzI4YWYw
  logLevel: info
  nodeAffinity: null
  nodeSelector: null
  replicas: 2
  resources:
    limits:
      memory: 750Mi
    requests:
      cpu: 10m
      memory: 250Mi
  tlsEnabled: true
  tlsMutual: false
  tolerations: null
appName: diagrid-agent
caCertPEM: |
  -----BEGIN CERTIFICATE-----
  MIIE8jCCA9qgAwIBAgISBLXrAaJ3Hj0Bi/Z/0WcHBSsDMA0GCSqGSIb3DQEBCwUA
  MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
  EwNSMTAwHhcNMjUwMzEwMDU0NjEyWhcNMjUwNjA4MDU0NjExWjAdMRswGQYDVQQD
  DBIqLnN0Zy5uLmRpYWdyaWQuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  AoIBAQC5WpUkXqTJ+vK8X/XPRh3Rqdp6wWPPvhz51jYixqKaihN2z8gbUnchYmjG
  iH+iYepXPe4k84Y4ZUgbCS4xxkcL2JNlZs/gPKgCkzDD1Y8vB+7Fsm5WwZBjb/YX
  LwULiORWWlp44Qk16bH/fW085fcf8JoFFuEVZ18pBUjPkWhdRoLxworDB5T9HSGt
  2ZAE47ufq+cV3vY5CMNQwpmrxDh4ljkT4vLHOsZGULcpFI2ErZecY9nN+XVOqQwa
  I6YJ6dA4j9X9Rj7rc0ZBTEVUe8P2ArPaCg98J9EeL4lyi4mBKf/agqN19wrjQLvg
  LeN4LoKJBPTKuKIPZiUOD6D3kqHxAgMBAAGjggIUMIICEDAOBgNVHQ8BAf8EBAMC
  BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
  HQYDVR0OBBYEFBK9F1ZkAYI6rEoc3XL/OOzuzpcGMB8GA1UdIwQYMBaAFLu8w0el
  5LypxsOkcgwQjaI14cjoMFcGCCsGAQUFBwEBBEswSTAiBggrBgEFBQcwAYYWaHR0
  cDovL3IxMC5vLmxlbmNyLm9yZzAjBggrBgEFBQcwAoYXaHR0cDovL3IxMC5pLmxl
  bmNyLm9yZy8wHQYDVR0RBBYwFIISKi5zdGcubi5kaWFncmlkLmlvMBMGA1UdIAQM
  MAowCAYGZ4EMAQIBMIIBAgYKKwYBBAHWeQIEAgSB8wSB8ADuAHUATnWjJ1yaEMM4
  W2zU3z9S6x3w4I4bjWnAsfpksWKaOd8AAAGVfsxzHgAABAMARjBEAiA7WQuh+40g
  qPu5GT9pc8cwWkqzaDwT/3kVWR7eX8i8iQIgEMZYE7THu7ePvclM2dFW4hNr/2V1
  qiIk3hRXun6h96EAdQBzICIPCBaK+fPEposKsmqaSgDu9XeFighNBQDUpUJEWQAA
  AZV+zHMbAAAEAwBGMEQCIBKrvFTAIvbQ7ckzBPfMBDeB6qc5dziJPfCC2BzCGhP1
  AiBfx5A4Z4uWgWHLzhnJuFsnMgzJAB2wG/3EZVYZZmBesDANBgkqhkiG9w0BAQsF
  AAOCAQEAhr6YVaRp8OnXuOwpGXkrkw/BGOFNOHX0aun6AytKptPIbttNV+pMPF24
  PwlPuomyEQFsQ72sCyeC/eUan/1J7M+htAONkIkAHAFkDLU6GCksPGtgORYyXl7q
  0W6FNTrB6cyKBUhE1Uqz4K5OFTcMmBs7MGM70m+UVpymVOQyv8PWGoZaUjgbwOkj
  kg+Uhfq0XlJCvNSyC3DMpZZx99WTY6bvWRSdFtO4tjpEFArFxGO/uag5VVswMRDX
  frmTrrK+FRsBCbswXtw8k1Cvye8BohDJJSKUilF1EfTq4PPGovFt134A9OucfpFB
  zCjNJyb1D/82EsKEFsbQ4DpSqQf5vQ==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP
  MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
  Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
  Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
  bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL
  YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a
  /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4
  FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR
  mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3
  DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG
  MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/
  AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbDpHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5
  tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKG
  Fmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwBAgEwJwYD
  VR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0B
  AQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6IOmQRJWjgVzPw139vaBw1bGWKCIL0vIo
  zwzn1OZDjCQiHcFCktEJr59L9MhwTyAWsVrdAfYf+B9haxQnsHKNY67u4s5Lzzfd
  u6PUzeetUK29v+PsPmI2cJkxp+iN3epi4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p9
  1n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4XaMJgnT9x3ies7msFtpKK5bDtotij/l0
  GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLEvwRdvCn294GPDF08U8lAkIv7tghluaQh
  1QnlE4SEN4LOECj8dsIGJXpGUk3aU3KkJz9icKy+aUgA+2cP21uh6NcDIS3XyfaZ
  QjmDQ993ChII8SXWupQZVBiIpcWO4RqZk3lr7Bz5MUCwzDIA359e57SSq5CCkY0N
  4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKgRJeZ9wygIaehbHFHFhcBaMDKpiZlBHyz
  rsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP2CX7dhHov+YhD+jozLW2p9W4959Bz2Ei
  RmqDtmiXLnzqTpXbI+suyCsohKRg6Un0RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLx
  KPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77AiC/ZidstK36dRILKz7OA54=
  -----END CERTIFICATE-----
clientCertPEM: ''
clientKeyPEM: ''
dapr:
  dapr_operator:
    resources:
      limits:
        cpu: '1'
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 100Mi
    watchInterval: 3m
  dapr_placement:
    resources:
      limits:
        cpu: '1'
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 75Mi
  dapr_rbac: {}
  dapr_scheduler:
    resources:
      limits:
        cpu: '1'
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 250Mi
  dapr_sentry:
    resources:
      limits:
        cpu: '1'
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 60Mi
  dapr_sidecar_injector:
    resources:
      limits:
        cpu: '1'
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 60Mi
  enabled: true
  global:
    ha:
      enabled: true
      replicaCount: 3
    logAsJson: true
    mtls:
      enabled: true
    registry: docker.io/daprio
daprRbacTargetServiceAccountName: diagrid-agent
global:
  agentId: 63b56921-de1e-432a-943e-4e2ded372027
  cloudUrl: cloudgrid.stg.n.diagrid.io:443
  customCA: ''
  isLocal: false
  isOpenShift: false
  kubernetesOs: linux
  mainServiceAccountName: diagrid-agent
  manifestId: 1.0.204
  namespace: diagrid-cloud
  namespaceDefault: diagrid-cloud
  orgId: d09f2663-104d-4767-b250-38ebfa18309a
  proxyConfig: null
  sccTargetServiceAccountName: diagrid-agent-logs-collector
isUseElevatedPermissions: false
labels: {}
mainClusterRoleBindingName: diagrid
mainClusterRoleName: diagrid
manifestApiVersion: diagrid.io/v1beta1
manifestKind: Manifest
metricsServer:
  enabled: true
otelLogsCollector:
  daprLogsURL: cloudgrid.stg.n.diagrid.io:443
  enabled: true
  goMemLimit: 600MiB
  image: >-
    us-central1-docker.pkg.dev/prj-common-p-shared-79896/reg-p-common-docker-public/diagrid-otel-collector:0.365.0
  isLocal: false
  isLogsLimited: false
  isOpenShift: false
  labels: {}
  logLevel: info
  memoryLimiter:
    checkInterval: 1s
    limitPercentage: 90
    spikeLimitPercentage: 20
  nodeAffinity: null
  nodeSelector: null
  remoteWriteAuthEnabled: true
  remoteWriteTlsInsecure: false
  remoteWriteURL: https://metrics.stg.n.diagrid.io/api/v1/push
  resources:
    limits:
      memory: 750Mi
    requests:
      cpu: 10m
      memory: 125Mi
  tlsEnabled: true
  tlsInsecure: false
  tolerations: null
otelMetricsCollector:
  enabled: true
  goMemLimit: 1638MiB
  image: >-
    us-central1-docker.pkg.dev/prj-common-p-shared-79896/reg-p-common-docker-public/diagrid-otel-collector:0.365.0
  labels: {}
  logLevel: info
  memoryLimiter:
    checkInterval: 1s
    limitPercentage: 90
    spikeLimitPercentage: 20
  nodeAffinity: null
  nodeSelector: null
  remoteWriteAuthEnabled: true
  remoteWriteTlsInsecure: false
  remoteWriteURL: https://metrics.stg.n.diagrid.io/api/v1/push
  replicas: 2
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 250Mi
  tlsEnabled: true
  tolerations: null
rbacUseDefaultSystemConfigName: false
sccName: diagrid-agent
