apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: dapr
    repoURL: https://dapr.github.io/helm-charts/
    targetRevision: 1.15.3  # Latest version as of knowledge cutoff
    helm:
      releaseName: dapr
      values: |
        global:
          ha:
            enabled: true
        dapr_dashboard:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true